# Generated by Django 5.1.5 on 2025-01-16 15:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_management', '0002_alter_product_options_product_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['-created_at', 'name']},
        ),
        migrations.RemoveField(
            model_name='product',
            name='user',
        ),
    ]
